replicaCount: 2

image: 
  repository: wolfycodes4fun/node-webapp
  tag: "v2"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

application:
  namespace: webapp

appConfig:
  APP_NAME: "dummy-webapp"

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
