---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-nodejs-deployment
  namespace: webapp
  labels:
    app: node-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-webapp
  template:
    metadata:
      labels:
        app: node-webapp
    spec:
      containers:
      - name: node-webapp
        image: wolfycodes4fun/node-webapp:v2
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: http
            containerPort: 5000
            protocol: TCP
        envFrom:
          - configMapRef:
              name: backend-config-map
