---
grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.local
    paths:
      - /

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true
